### ISSUE TITLE
Failed to determine version of * while parsing a yarn.lock - please report this!

### ISSUE THREAD

**Issue by davift** [google/osv-scanner#142] opened 2023-01-12 19:32 UTC
Dear developers,

By scanning few (100+) repositories I got a list of requests to report in a couple of them:

```
Failed to determine version of @babel/parser while parsing a yarn.lock - please report this!
Failed to determine version of @colors/colors while parsing a yarn.lock - please report this!
Failed to determine version of @cypress/request while parsing a yarn.lock - please report this!
Failed to determine version of @cypress/xvfb while parsing a yarn.lock - please report this!
Failed to determine version of @eslint/eslintrc while parsing a yarn.lock - please report this!
Failed to determine version of @fortawesome/fontawesome-free while parsing a yarn.lock - please report this!
Failed to determine version of @hapi/hoek while parsing a yarn.lock - please report this!
Failed to determine version of @hapi/topo while parsing a yarn.lock - please report this!
Failed to determine version of @humanwhocodes/config-array while parsing a yarn.lock - please report this!
Failed to determine version of @humanwhocodes/object-schema while parsing a yarn.lock - please report this!
Failed to determine version of @nodelib/fs.scandir while parsing a yarn.lock - please report this!
Failed to determine version of @nodelib/fs.stat while parsing a yarn.lock - please report this!
Failed to determine version of @nodelib/fs.walk while parsing a yarn.lock - please report this!
Failed to determine version of @rushstack/eslint-patch while parsing a yarn.lock - please report this!
Failed to determine version of @sideway/address while parsing a yarn.lock - please report this!
Failed to determine version of @sideway/formula while parsing a yarn.lock - please report this!
Failed to determine version of @sideway/pinpoint while parsing a yarn.lock - please report this!
Failed to determine version of @tootallnate/once while parsing a yarn.lock - please report this!
Failed to determine version of @types/chai while parsing a yarn.lock - please report this!
Failed to determine version of @types/chai-subset while parsing a yarn.lock - please report this!
Failed to determine version of @types/jsdom while parsing a yarn.lock - please report this!
Failed to determine version of @types/json-schema while parsing a yarn.lock - please report this!
Failed to determine version of @types/node while parsing a yarn.lock - please report this!
Failed to determine version of @types/parse5 while parsing a yarn.lock - please report this!
Failed to determine version of @types/sinonjs__fake-timers while parsing a yarn.lock - please report this!
Failed to determine version of @types/sizzle while parsing a yarn.lock - please report this!
Failed to determine version of @types/tough-cookie while parsing a yarn.lock - please report this!
Failed to determine version of @types/yauzl while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/eslint-plugin while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/parser while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/scope-manager while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/type-utils while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/types while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/typescript-estree while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/utils while parsing a yarn.lock - please report this!
Failed to determine version of @typescript-eslint/visitor-keys while parsing a yarn.lock - please report this!
Failed to determine version of @vitejs/plugin-vue while parsing a yarn.lock - please report this!
Failed to determine version of @volar/code-gen while parsing a yarn.lock - please report this!
Failed to determine version of @volar/language-core while parsing a yarn.lock - please report this!
Failed to determine version of @volar/source-map while parsing a yarn.lock - please report this!
Failed to determine version of @volar/typescript while parsing a yarn.lock - please report this!
Failed to determine version of @volar/vue-code-gen while parsing a yarn.lock - please report this!
Failed to determine version of @volar/vue-language-core while parsing a yarn.lock - please report this!
Failed to determine version of @volar/vue-typescript while parsing a yarn.lock - please report this!
Failed to determine version of @vue/compiler-core while parsing a yarn.lock - please report this!
Failed to determine version of @vue/compiler-dom while parsing a yarn.lock - please report this!
Failed to determine version of @vue/compiler-sfc while parsing a yarn.lock - please report this!
Failed to determine version of @vue/compiler-ssr while parsing a yarn.lock - please report this!
Failed to determine version of @vue/devtools-api while parsing a yarn.lock - please report this!
Failed to determine version of @vue/eslint-config-prettier while parsing a yarn.lock - please report this!
Failed to determine version of @vue/eslint-config-typescript while parsing a yarn.lock - please report this!
Failed to determine version of @vue/reactivity while parsing a yarn.lock - please report this!
Failed to determine version of @vue/reactivity-transform while parsing a yarn.lock - please report this!
Failed to determine version of @vue/runtime-core while parsing a yarn.lock - please report this!
Failed to determine version of @vue/runtime-dom while parsing a yarn.lock - please report this!
Failed to determine version of @vue/server-renderer while parsing a yarn.lock - please report this!
Failed to determine version of @vue/shared while parsing a yarn.lock - please report this!
Failed to determine version of @vue/test-utils while parsing a yarn.lock - please report this!
Failed to determine version of @vue/tsconfig while parsing a yarn.lock - please report this!
Failed to determine version of abab while parsing a yarn.lock - please report this!
Failed to determine version of acorn while parsing a yarn.lock - please report this!
Failed to determine version of acorn-globals while parsing a yarn.lock - please report this!
Failed to determine version of acorn-jsx while parsing a yarn.lock - please report this!
Failed to determine version of acorn-walk while parsing a yarn.lock - please report this!
Failed to determine version of agent-base while parsing a yarn.lock - please report this!
Failed to determine version of aggregate-error while parsing a yarn.lock - please report this!
Failed to determine version of ajv while parsing a yarn.lock - please report this!
Failed to determine version of ansi-colors while parsing a yarn.lock - please report this!
Failed to determine version of ansi-escapes while parsing a yarn.lock - please report this!
Failed to determine version of ansi-regex while parsing a yarn.lock - please report this!
Failed to determine version of ansi-styles while parsing a yarn.lock - please report this!
Failed to determine version of anymatch while parsing a yarn.lock - please report this!
Failed to determine version of arch while parsing a yarn.lock - please report this!
Failed to determine version of argparse while parsing a yarn.lock - please report this!
Failed to determine version of array-union while parsing a yarn.lock - please report this!
Failed to determine version of asn1 while parsing a yarn.lock - please report this!
Failed to determine version of assert-plus while parsing a yarn.lock - please report this!
Failed to determine version of assertion-error while parsing a yarn.lock - please report this!
Failed to determine version of astral-regex while parsing a yarn.lock - please report this!
Failed to determine version of async while parsing a yarn.lock - please report this!
Failed to determine version of asynckit while parsing a yarn.lock - please report this!
Failed to determine version of at-least-node while parsing a yarn.lock - please report this!
Failed to determine version of aws-sign2 while parsing a yarn.lock - please report this!
Failed to determine version of aws4 while parsing a yarn.lock - please report this!
Failed to determine version of axios while parsing a yarn.lock - please report this!
Failed to determine version of babel-runtime while parsing a yarn.lock - please report this!
Failed to determine version of balanced-match while parsing a yarn.lock - please report this!
Failed to determine version of base64-js while parsing a yarn.lock - please report this!
Failed to determine version of bcrypt-pbkdf while parsing a yarn.lock - please report this!
Failed to determine version of binary-extensions while parsing a yarn.lock - please report this!
Failed to determine version of blob-util while parsing a yarn.lock - please report this!
Failed to determine version of bluebird while parsing a yarn.lock - please report this!
Failed to determine version of boolbase while parsing a yarn.lock - please report this!
Failed to determine version of brace-expansion while parsing a yarn.lock - please report this!
Failed to determine version of braces while parsing a yarn.lock - please report this!
Failed to determine version of browser-process-hrtime while parsing a yarn.lock - please report this!
Failed to determine version of buffer while parsing a yarn.lock - please report this!
Failed to determine version of buffer-crc32 while parsing a yarn.lock - please report this!
Failed to determine version of cachedir while parsing a yarn.lock - please report this!
Failed to determine version of callsites while parsing a yarn.lock - please report this!
Failed to determine version of caseless while parsing a yarn.lock - please report this!
Failed to determine version of chai while parsing a yarn.lock - please report this!
Failed to determine version of chalk while parsing a yarn.lock - please report this!
Failed to determine version of check-error while parsing a yarn.lock - please report this!
Failed to determine version of check-more-types while parsing a yarn.lock - please report this!
Failed to determine version of chokidar while parsing a yarn.lock - please report this!
Failed to determine version of ci-info while parsing a yarn.lock - please report this!
Failed to determine version of clean-stack while parsing a yarn.lock - please report this!
Failed to determine version of cli-cursor while parsing a yarn.lock - please report this!
Failed to determine version of cli-table3 while parsing a yarn.lock - please report this!
Failed to determine version of cli-truncate while parsing a yarn.lock - please report this!
Failed to determine version of color-convert while parsing a yarn.lock - please report this!
Failed to determine version of color-name while parsing a yarn.lock - please report this!
Failed to determine version of colorette while parsing a yarn.lock - please report this!
Failed to determine version of combined-stream while parsing a yarn.lock - please report this!
Failed to determine version of commander while parsing a yarn.lock - please report this!
Failed to determine version of common-tags while parsing a yarn.lock - please report this!
Failed to determine version of concat-map while parsing a yarn.lock - please report this!
Failed to determine version of core-js while parsing a yarn.lock - please report this!
Failed to determine version of core-util-is while parsing a yarn.lock - please report this!
Failed to determine version of cross-spawn while parsing a yarn.lock - please report this!
Failed to determine version of cssesc while parsing a yarn.lock - please report this!
Failed to determine version of cssom while parsing a yarn.lock - please report this!
Failed to determine version of cssstyle while parsing a yarn.lock - please report this!
Failed to determine version of csstype while parsing a yarn.lock - please report this!
Failed to determine version of cypress while parsing a yarn.lock - please report this!
Failed to determine version of dashdash while parsing a yarn.lock - please report this!
Failed to determine version of data-urls while parsing a yarn.lock - please report this!
Failed to determine version of dayjs while parsing a yarn.lock - please report this!
Failed to determine version of de-indent while parsing a yarn.lock - please report this!
Failed to determine version of debug while parsing a yarn.lock - please report this!
Failed to determine version of decimal.js while parsing a yarn.lock - please report this!
Failed to determine version of deep-eql while parsing a yarn.lock - please report this!
Failed to determine version of deep-is while parsing a yarn.lock - please report this!
Failed to determine version of delayed-stream while parsing a yarn.lock - please report this!
Failed to determine version of dir-glob while parsing a yarn.lock - please report this!
Failed to determine version of doctrine while parsing a yarn.lock - please report this!
Failed to determine version of domexception while parsing a yarn.lock - please report this!
Failed to determine version of duplexer while parsing a yarn.lock - please report this!
Failed to determine version of ecc-jsbn while parsing a yarn.lock - please report this!
Failed to determine version of emoji-regex while parsing a yarn.lock - please report this!
Failed to determine version of end-of-stream while parsing a yarn.lock - please report this!
Failed to determine version of enquirer while parsing a yarn.lock - please report this!
Failed to determine version of esbuild while parsing a yarn.lock - please report this!
Failed to determine version of esbuild-darwin-64 while parsing a yarn.lock - please report this!
Failed to determine version of escape-string-regexp while parsing a yarn.lock - please report this!
Failed to determine version of escodegen while parsing a yarn.lock - please report this!
Failed to determine version of eslint while parsing a yarn.lock - please report this!
Failed to determine version of eslint-config-prettier while parsing a yarn.lock - please report this!
Failed to determine version of eslint-plugin-cypress while parsing a yarn.lock - please report this!
Failed to determine version of eslint-plugin-prettier while parsing a yarn.lock - please report this!
Failed to determine version of eslint-plugin-vue while parsing a yarn.lock - please report this!
Failed to determine version of eslint-scope while parsing a yarn.lock - please report this!
Failed to determine version of eslint-utils while parsing a yarn.lock - please report this!
Failed to determine version of eslint-visitor-keys while parsing a yarn.lock - please report this!
Failed to determine version of espree while parsing a yarn.lock - please report this!
Failed to determine version of esprima while parsing a yarn.lock - please report this!
Failed to determine version of esquery while parsing a yarn.lock - please report this!
Failed to determine version of esrecurse while parsing a yarn.lock - please report this!
Failed to determine version of estraverse while parsing a yarn.lock - please report this!
Failed to determine version of estree-walker while parsing a yarn.lock - please report this!
Failed to determine version of esutils while parsing a yarn.lock - please report this!
Failed to determine version of event-stream while parsing a yarn.lock - please report this!
Failed to determine version of eventemitter2 while parsing a yarn.lock - please report this!
Failed to determine version of execa while parsing a yarn.lock - please report this!
Failed to determine version of executable while parsing a yarn.lock - please report this!
Failed to determine version of extend while parsing a yarn.lock - please report this!
Failed to determine version of extract-zip while parsing a yarn.lock - please report this!
Failed to determine version of extsprintf while parsing a yarn.lock - please report this!
Failed to determine version of fast-deep-equal while parsing a yarn.lock - please report this!
Failed to determine version of fast-diff while parsing a yarn.lock - please report this!
Failed to determine version of fast-glob while parsing a yarn.lock - please report this!
Failed to determine version of fast-json-stable-stringify while parsing a yarn.lock - please report this!
Failed to determine version of fast-levenshtein while parsing a yarn.lock - please report this!
Failed to determine version of fastq while parsing a yarn.lock - please report this!
Failed to determine version of fd-slicer while parsing a yarn.lock - please report this!
Failed to determine version of figures while parsing a yarn.lock - please report this!
Failed to determine version of file-entry-cache while parsing a yarn.lock - please report this!
Failed to determine version of fill-range while parsing a yarn.lock - please report this!
Failed to determine version of flat-cache while parsing a yarn.lock - please report this!
Failed to determine version of flatted while parsing a yarn.lock - please report this!
Failed to determine version of follow-redirects while parsing a yarn.lock - please report this!
Failed to determine version of forever-agent while parsing a yarn.lock - please report this!
Failed to determine version of form-data while parsing a yarn.lock - please report this!
Failed to determine version of from while parsing a yarn.lock - please report this!
Failed to determine version of fs-extra while parsing a yarn.lock - please report this!
Failed to determine version of fs.realpath while parsing a yarn.lock - please report this!
Failed to determine version of fsevents while parsing a yarn.lock - please report this!
Failed to determine version of function-bind while parsing a yarn.lock - please report this!
Failed to determine version of functional-red-black-tree while parsing a yarn.lock - please report this!
Failed to determine version of get-func-name while parsing a yarn.lock - please report this!
Failed to determine version of get-stream while parsing a yarn.lock - please report this!
Failed to determine version of getos while parsing a yarn.lock - please report this!
Failed to determine version of getpass while parsing a yarn.lock - please report this!
Failed to determine version of glob while parsing a yarn.lock - please report this!
Failed to determine version of glob-parent while parsing a yarn.lock - please report this!
Failed to determine version of global-dirs while parsing a yarn.lock - please report this!
Failed to determine version of globals while parsing a yarn.lock - please report this!
Failed to determine version of globby while parsing a yarn.lock - please report this!
Failed to determine version of graceful-fs while parsing a yarn.lock - please report this!
Failed to determine version of hammerjs while parsing a yarn.lock - please report this!
Failed to determine version of has while parsing a yarn.lock - please report this!
Failed to determine version of has-flag while parsing a yarn.lock - please report this!
Failed to determine version of he while parsing a yarn.lock - please report this!
Failed to determine version of html-encoding-sniffer while parsing a yarn.lock - please report this!
Failed to determine version of http-proxy-agent while parsing a yarn.lock - please report this!
Failed to determine version of http-signature while parsing a yarn.lock - please report this!
Failed to determine version of https-proxy-agent while parsing a yarn.lock - please report this!
Failed to determine version of human-signals while parsing a yarn.lock - please report this!
Failed to determine version of iconv-lite while parsing a yarn.lock - please report this!
Failed to determine version of ieee754 while parsing a yarn.lock - please report this!
Failed to determine version of ignore while parsing a yarn.lock - please report this!
Failed to determine version of immutable while parsing a yarn.lock - please report this!
Failed to determine version of import-fresh while parsing a yarn.lock - please report this!
Failed to determine version of imurmurhash while parsing a yarn.lock - please report this!
Failed to determine version of indent-string while parsing a yarn.lock - please report this!
Failed to determine version of inflight while parsing a yarn.lock - please report this!
Failed to determine version of inherits while parsing a yarn.lock - please report this!
Failed to determine version of ini while parsing a yarn.lock - please report this!
Failed to determine version of is-binary-path while parsing a yarn.lock - please report this!
Failed to determine version of is-ci while parsing a yarn.lock - please report this!
Failed to determine version of is-core-module while parsing a yarn.lock - please report this!
Failed to determine version of is-extglob while parsing a yarn.lock - please report this!
Failed to determine version of is-fullwidth-code-point while parsing a yarn.lock - please report this!
Failed to determine version of is-glob while parsing a yarn.lock - please report this!
Failed to determine version of is-installed-globally while parsing a yarn.lock - please report this!
Failed to determine version of is-number while parsing a yarn.lock - please report this!
Failed to determine version of is-path-inside while parsing a yarn.lock - please report this!
Failed to determine version of is-potential-custom-element-name while parsing a yarn.lock - please report this!
Failed to determine version of is-stream while parsing a yarn.lock - please report this!
Failed to determine version of is-typedarray while parsing a yarn.lock - please report this!
Failed to determine version of is-unicode-supported while parsing a yarn.lock - please report this!
Failed to determine version of isexe while parsing a yarn.lock - please report this!
Failed to determine version of isstream while parsing a yarn.lock - please report this!
Failed to determine version of joi while parsing a yarn.lock - please report this!
Failed to determine version of js-yaml while parsing a yarn.lock - please report this!
Failed to determine version of jsbn while parsing a yarn.lock - please report this!
Failed to determine version of jsdom while parsing a yarn.lock - please report this!
Failed to determine version of json-schema while parsing a yarn.lock - please report this!
Failed to determine version of json-schema-traverse while parsing a yarn.lock - please report this!
Failed to determine version of json-stable-stringify-without-jsonify while parsing a yarn.lock - please report this!
Failed to determine version of json-stringify-safe while parsing a yarn.lock - please report this!
Failed to determine version of jsonfile while parsing a yarn.lock - please report this!
Failed to determine version of jsprim while parsing a yarn.lock - please report this!
Failed to determine version of lazy-ass while parsing a yarn.lock - please report this!
Failed to determine version of levn while parsing a yarn.lock - please report this!
Failed to determine version of listr2 while parsing a yarn.lock - please report this!
Failed to determine version of local-pkg while parsing a yarn.lock - please report this!
Failed to determine version of lodash while parsing a yarn.lock - please report this!
Failed to determine version of lodash.merge while parsing a yarn.lock - please report this!
Failed to determine version of lodash.once while parsing a yarn.lock - please report this!
Failed to determine version of log-symbols while parsing a yarn.lock - please report this!
Failed to determine version of log-update while parsing a yarn.lock - please report this!
Failed to determine version of loupe while parsing a yarn.lock - please report this!
Failed to determine version of lru-cache while parsing a yarn.lock - please report this!
Failed to determine version of magic-string while parsing a yarn.lock - please report this!
Failed to determine version of map-stream while parsing a yarn.lock - please report this!
Failed to determine version of merge-stream while parsing a yarn.lock - please report this!
Failed to determine version of merge2 while parsing a yarn.lock - please report this!
Failed to determine version of micromatch while parsing a yarn.lock - please report this!
Failed to determine version of mime-db while parsing a yarn.lock - please report this!
Failed to determine version of mime-types while parsing a yarn.lock - please report this!
Failed to determine version of mimic-fn while parsing a yarn.lock - please report this!
Failed to determine version of minimatch while parsing a yarn.lock - please report this!
Failed to determine version of minimist while parsing a yarn.lock - please report this!
Failed to determine version of ms while parsing a yarn.lock - please report this!
Failed to determine version of muggle-string while parsing a yarn.lock - please report this!
Failed to determine version of nanoid while parsing a yarn.lock - please report this!
Failed to determine version of natural-compare while parsing a yarn.lock - please report this!
Failed to determine version of normalize-path while parsing a yarn.lock - please report this!
Failed to determine version of npm-run-path while parsing a yarn.lock - please report this!
Failed to determine version of nth-check while parsing a yarn.lock - please report this!
Failed to determine version of nwsapi while parsing a yarn.lock - please report this!
Failed to determine version of once while parsing a yarn.lock - please report this!
Failed to determine version of onetime while parsing a yarn.lock - please report this!
Failed to determine version of optionator while parsing a yarn.lock - please report this!
Failed to determine version of ospath while parsing a yarn.lock - please report this!
Failed to determine version of p-map while parsing a yarn.lock - please report this!
Failed to determine version of pannellum while parsing a yarn.lock - please report this!
Failed to determine version of parent-module while parsing a yarn.lock - please report this!
Failed to determine version of parse5 while parsing a yarn.lock - please report this!
Failed to determine version of path-is-absolute while parsing a yarn.lock - please report this!
Failed to determine version of path-key while parsing a yarn.lock - please report this!
Failed to determine version of path-parse while parsing a yarn.lock - please report this!
Failed to determine version of path-type while parsing a yarn.lock - please report this!
Failed to determine version of pathval while parsing a yarn.lock - please report this!
Failed to determine version of pause-stream while parsing a yarn.lock - please report this!
Failed to determine version of pend while parsing a yarn.lock - please report this!
Failed to determine version of performance-now while parsing a yarn.lock - please report this!
Failed to determine version of picocolors while parsing a yarn.lock - please report this!
Failed to determine version of picomatch while parsing a yarn.lock - please report this!
Failed to determine version of pify while parsing a yarn.lock - please report this!
Failed to determine version of pinia while parsing a yarn.lock - please report this!
Failed to determine version of postcss while parsing a yarn.lock - please report this!
Failed to determine version of postcss-selector-parser while parsing a yarn.lock - please report this!
Failed to determine version of prelude-ls while parsing a yarn.lock - please report this!
Failed to determine version of prettier while parsing a yarn.lock - please report this!
Failed to determine version of prettier-linter-helpers while parsing a yarn.lock - please report this!
Failed to determine version of pretty-bytes while parsing a yarn.lock - please report this!
Failed to determine version of proxy-from-env while parsing a yarn.lock - please report this!
Failed to determine version of ps-tree while parsing a yarn.lock - please report this!
Failed to determine version of psl while parsing a yarn.lock - please report this!
Failed to determine version of pump while parsing a yarn.lock - please report this!
Failed to determine version of punycode while parsing a yarn.lock - please report this!
Failed to determine version of qs while parsing a yarn.lock - please report this!
Failed to determine version of queue-microtask while parsing a yarn.lock - please report this!
Failed to determine version of readdirp while parsing a yarn.lock - please report this!
Failed to determine version of regenerator-runtime while parsing a yarn.lock - please report this!
Failed to determine version of regexpp while parsing a yarn.lock - please report this!
Failed to determine version of request-progress while parsing a yarn.lock - please report this!
Failed to determine version of resolve while parsing a yarn.lock - please report this!
Failed to determine version of resolve-from while parsing a yarn.lock - please report this!
Failed to determine version of restore-cursor while parsing a yarn.lock - please report this!
Failed to determine version of reusify while parsing a yarn.lock - please report this!
Failed to determine version of rfdc while parsing a yarn.lock - please report this!
Failed to determine version of rimraf while parsing a yarn.lock - please report this!
Failed to determine version of rollup while parsing a yarn.lock - please report this!
Failed to determine version of run-parallel while parsing a yarn.lock - please report this!
Failed to determine version of rxjs while parsing a yarn.lock - please report this!
Failed to determine version of safe-buffer while parsing a yarn.lock - please report this!
Failed to determine version of safer-buffer while parsing a yarn.lock - please report this!
Failed to determine version of sass while parsing a yarn.lock - please report this!
Failed to determine version of saxes while parsing a yarn.lock - please report this!
Failed to determine version of semver while parsing a yarn.lock - please report this!
Failed to determine version of shebang-command while parsing a yarn.lock - please report this!
Failed to determine version of shebang-regex while parsing a yarn.lock - please report this!
Failed to determine version of signal-exit while parsing a yarn.lock - please report this!
Failed to determine version of slash while parsing a yarn.lock - please report this!
Failed to determine version of slice-ansi while parsing a yarn.lock - please report this!
Failed to determine version of source-map while parsing a yarn.lock - please report this!
Failed to determine version of source-map-js while parsing a yarn.lock - please report this!
Failed to determine version of sourcemap-codec while parsing a yarn.lock - please report this!
Failed to determine version of split while parsing a yarn.lock - please report this!
Failed to determine version of sshpk while parsing a yarn.lock - please report this!
Failed to determine version of start-server-and-test while parsing a yarn.lock - please report this!
Failed to determine version of stream-combiner while parsing a yarn.lock - please report this!
Failed to determine version of string-width while parsing a yarn.lock - please report this!
Failed to determine version of strip-ansi while parsing a yarn.lock - please report this!
Failed to determine version of strip-final-newline while parsing a yarn.lock - please report this!
Failed to determine version of strip-json-comments while parsing a yarn.lock - please report this!
Failed to determine version of supports-color while parsing a yarn.lock - please report this!
Failed to determine version of supports-preserve-symlinks-flag while parsing a yarn.lock - please report this!
Failed to determine version of symbol-tree while parsing a yarn.lock - please report this!
Failed to determine version of text-table while parsing a yarn.lock - please report this!
Failed to determine version of throttleit while parsing a yarn.lock - please report this!
Failed to determine version of through while parsing a yarn.lock - please report this!
Failed to determine version of tinypool while parsing a yarn.lock - please report this!
Failed to determine version of tinyspy while parsing a yarn.lock - please report this!
Failed to determine version of tmp while parsing a yarn.lock - please report this!
Failed to determine version of to-regex-range while parsing a yarn.lock - please report this!
Failed to determine version of tough-cookie while parsing a yarn.lock - please report this!
Failed to determine version of tr46 while parsing a yarn.lock - please report this!
Failed to determine version of tslib while parsing a yarn.lock - please report this!
Failed to determine version of tsutils while parsing a yarn.lock - please report this!
Failed to determine version of tunnel-agent while parsing a yarn.lock - please report this!
Failed to determine version of tweetnacl while parsing a yarn.lock - please report this!
Failed to determine version of type-check while parsing a yarn.lock - please report this!
Failed to determine version of type-detect while parsing a yarn.lock - please report this!
Failed to determine version of type-fest while parsing a yarn.lock - please report this!
Failed to determine version of typescript while parsing a yarn.lock - please report this!
Failed to determine version of universalify while parsing a yarn.lock - please report this!
Failed to determine version of untildify while parsing a yarn.lock - please report this!
Failed to determine version of uri-js while parsing a yarn.lock - please report this!
Failed to determine version of util-deprecate while parsing a yarn.lock - please report this!
Failed to determine version of uuid while parsing a yarn.lock - please report this!
Failed to determine version of v8-compile-cache while parsing a yarn.lock - please report this!
Failed to determine version of verror while parsing a yarn.lock - please report this!
Failed to determine version of vite while parsing a yarn.lock - please report this!
Failed to determine version of vitest while parsing a yarn.lock - please report this!
Failed to determine version of vue while parsing a yarn.lock - please report this!
Failed to determine version of vue-360 while parsing a yarn.lock - please report this!
Failed to determine version of vue-demi while parsing a yarn.lock - please report this!
Failed to determine version of vue-eslint-parser while parsing a yarn.lock - please report this!
Failed to determine version of vue-router while parsing a yarn.lock - please report this!
Failed to determine version of vue-template-compiler while parsing a yarn.lock - please report this!
Failed to determine version of vue-tsc while parsing a yarn.lock - please report this!
Failed to determine version of vue2-hammer while parsing a yarn.lock - please report this!
Failed to determine version of vue3-easy-data-table while parsing a yarn.lock - please report this!
Failed to determine version of vue3-touch-events while parsing a yarn.lock - please report this!
Failed to determine version of vuetify while parsing a yarn.lock - please report this!
Failed to determine version of w3c-hr-time while parsing a yarn.lock - please report this!
Failed to determine version of w3c-xmlserializer while parsing a yarn.lock - please report this!
Failed to determine version of wait-on while parsing a yarn.lock - please report this!
Failed to determine version of webidl-conversions while parsing a yarn.lock - please report this!
Failed to determine version of whatwg-encoding while parsing a yarn.lock - please report this!
Failed to determine version of whatwg-mimetype while parsing a yarn.lock - please report this!
Failed to determine version of whatwg-url while parsing a yarn.lock - please report this!
Failed to determine version of which while parsing a yarn.lock - please report this!
Failed to determine version of word-wrap while parsing a yarn.lock - please report this!
Failed to determine version of wrap-ansi while parsing a yarn.lock - please report this!
Failed to determine version of wrappy while parsing a yarn.lock - please report this!
Failed to determine version of ws while parsing a yarn.lock - please report this!
Failed to determine version of xml-name-validator while parsing a yarn.lock - please report this!
Failed to determine version of xmlchars while parsing a yarn.lock - please report this!
Failed to determine version of yallist while parsing a yarn.lock - please report this!
Failed to determine version of yauzl while parsing a yarn.lock - please report this!
```

[yarn.lock.txt](https://github.com/google/osv-scanner/files/10405363/yarn.lock.txt)

Regards,

**Comment by G-Rath** [comment] 2023-01-12 20:02
This looks like a duplicate of #102, which is because the `yarn.lock` file has keys quoted - I believe that this is an invalid lockfile since I've not been able to reproduce it even using the oldest version of `yarn` I could get working, and the original user reported that running `yarn install` did resolve the issue which further indicates the `yarn.lock` was invalid.

It is something that'd be very easy to support (I've already got a patch for it) but I'd like to try and better understand how such a lockfile is being generated first if possible.

**Closed** 2023-01-12 20:09 UTC
