### ISSUE TITLE
Issue with Blank Package Versions in JSON Output when Scanning composer.lock File

### ISSUE THREAD

**Issue by AnkitVachhani** [google/osv-scanner#735] opened 2024-01-04 17:19 UTC
### Description
When scanning the `composer.lock` file using JSON output, the package version information is returned as blank.

### Attachments
- [composer.lock](https://github.com/google/osv-scanner/files/13833609/composer.lock.zip)
- [JSON Output File](https://github.com/google/osv-scanner/files/13833603/test.json)

### Environment
- Operating System: CentOS
- Scanner Version: v1.5.0

**Comment by another-rex** [comment] 2024-01-05 02:20
Thanks for catching this issue! 

It is caused by both the package version and git repo and commit existing at the same time. I made a fix in #736 and it should be fixed in the next release.

**Closed** 2024-01-09 05:16 UTC
Labels: bug
