### ISSUE TITLE
Alpine packaging: Tests break if other .gitignore files are present in parent directories

### ISSUE THREAD

**Issue by kpcyrd** [google/osv-scanner#286] opened 2023-03-11 14:13 UTC
The tests for the [1.2.0 upgrade](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/45010) are currently failing in Alpine: https://gitlab.alpinelinux.org/ptrcnull/aports/-/jobs/989373

The errors look like this:

```
--- FAIL: TestRun (0.00s)
    --- FAIL: TestRun/#03 (1.78s)
        main_test.go:273: stderr
             got:
            /builds/ptrcnull/aports/community/osv-scanner/src/osv-scanner-1.2.0/cmd/osv-scanner/fixtures/locks-many/not-a-lockfile.toml was not scanned because it is excluded by a .gitignore file. Use --no-ignore to scan it.
            No package sources found, --help for usage information.
            
             want:
            No package sources found, --help for usage information.
    --- FAIL: TestRun/#10 (1.78s)
        main_test.go:273: cli exited with code 128, not 0
        main_test.go:273: stdout
             got:
            {
              "results": null
            }
            
             want:
            {
              "results": []
            }
        main_test.go:273: stderr
             got:
            Scanning dir ./fixtures/locks-many/composer.lock
            /builds/ptrcnull/aports/community/osv-scanner/src/osv-scanner-1.2.0/cmd/osv-scanner/fixtures/locks-many/composer.lock was not scanned because it is excluded by a .gitignore file. Use --no-ignore to scan it.
            No package sources found, --help for usage information.
            
             want:
            Scanning dir ./fixtures/locks-many/composer.lock
            Scanned %%/fixtures/locks-many/composer.lock file and found 1 packages
```

I think this is because osv-scanner recognizes that the build path `/builds/ptrcnull/aports/community/osv-scanner/src/osv-scanner-1.2.0/` is inside of a git repository `/builds/ptrcnull/aports/` and then picks up a [`.gitignore`](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/.gitignore) file from outside the buildpath at `/builds/ptrcnull/aports/.gitignore`. This file excludes `/builds/ptrcnull/aports/community/osv-scanner/src/`, which causes osv-scanner tests to dismiss all test files, causing the tests to fail.

Not sure what's the best way to solve this, but figured I might share my analysis.

**Comment by another-rex** [comment] 2023-03-12 23:13
It seems like we might be able to use [GIT_CEILING_DIRECTORY](https://git-scm.com/docs/git#Documentation/git.txt-codeGITCEILINGDIRECTORIEScode), according to the [comment by alice](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/45010#note_295718) in the Alpine PR.

@michaelkedar Can you take a look?

**Comment by michaelkedar** [comment] 2023-03-13 00:02
This is actually a consequence of #209. GIT_CEILING_DIRECTORY could be a temporary fix for this for now.

**Comment by michaelkedar** [comment] 2023-03-13 00:27
Actually ,I was wrong and it's not related. The problem is that the tests assume that osv-scanner is in a git repository, which is not the case when downloading the source files

**Closed** 2023-03-14 02:55 UTC
Labels: bug
